version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    steps:
      - checkout
      - run: cd com.hikidgo
      - run: npm install
      - run: ng build --prod --build-optimizer --no-progress
      - store_artifacts:
          path: ~/work/